DROP DATABASE IF EXISTS GAMEDB;

CREATE DATABASE GAMEDB;

use GAMEDB;

CREATE TABLE GAME (
    GAME_ID int NOT NULL AUTO_INCREMENT,
    GAME_GUESSES int NOT NULL,
    GAME_COUNT int NOT NULL,
    PRIMARY KEY (GAME_ID)
);

INSERT INTO GAME (GAME_COUNT) VALUES (0);